// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcounter.proto

/*
Package tcounter is a generated protocol buffer package.

It is generated from these files:
	tcounter.proto

It has these top-level messages:
	ValueTick
	CounterMapped
	SendTableReq
	EmptyRsp
*/
package tcounter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueTick struct {
	Time  int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Sum   int64  `protobuf:"varint,2,opt,name=sum" json:"sum,omitempty"`
	Count uint64 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *ValueTick) Reset()                    { *m = ValueTick{} }
func (m *ValueTick) String() string            { return proto.CompactTextString(m) }
func (*ValueTick) ProtoMessage()               {}
func (*ValueTick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ValueTick) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ValueTick) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *ValueTick) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CounterMapped struct {
	ValueList []*ValueTick `protobuf:"bytes,1,rep,name=valueList" json:"valueList,omitempty"`
}

func (m *CounterMapped) Reset()                    { *m = CounterMapped{} }
func (m *CounterMapped) String() string            { return proto.CompactTextString(m) }
func (*CounterMapped) ProtoMessage()               {}
func (*CounterMapped) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CounterMapped) GetValueList() []*ValueTick {
	if m != nil {
		return m.ValueList
	}
	return nil
}

type SendTableReq struct {
	Table map[uint32]*CounterMapped `protobuf:"bytes,1,rep,name=table" json:"table,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SendTableReq) Reset()                    { *m = SendTableReq{} }
func (m *SendTableReq) String() string            { return proto.CompactTextString(m) }
func (*SendTableReq) ProtoMessage()               {}
func (*SendTableReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendTableReq) GetTable() map[uint32]*CounterMapped {
	if m != nil {
		return m.Table
	}
	return nil
}

type EmptyRsp struct {
}

func (m *EmptyRsp) Reset()                    { *m = EmptyRsp{} }
func (m *EmptyRsp) String() string            { return proto.CompactTextString(m) }
func (*EmptyRsp) ProtoMessage()               {}
func (*EmptyRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*ValueTick)(nil), "tcounter.ValueTick")
	proto.RegisterType((*CounterMapped)(nil), "tcounter.CounterMapped")
	proto.RegisterType((*SendTableReq)(nil), "tcounter.SendTableReq")
	proto.RegisterType((*EmptyRsp)(nil), "tcounter.EmptyRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CounterService service

type CounterServiceClient interface {
	SendTable(ctx context.Context, in *SendTableReq, opts ...grpc.CallOption) (*EmptyRsp, error)
}

type counterServiceClient struct {
	cc *grpc.ClientConn
}

func NewCounterServiceClient(cc *grpc.ClientConn) CounterServiceClient {
	return &counterServiceClient{cc}
}

func (c *counterServiceClient) SendTable(ctx context.Context, in *SendTableReq, opts ...grpc.CallOption) (*EmptyRsp, error) {
	out := new(EmptyRsp)
	err := grpc.Invoke(ctx, "/tcounter.CounterService/sendTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CounterService service

type CounterServiceServer interface {
	SendTable(context.Context, *SendTableReq) (*EmptyRsp, error)
}

func RegisterCounterServiceServer(s *grpc.Server, srv CounterServiceServer) {
	s.RegisterService(&_CounterService_serviceDesc, srv)
}

func _CounterService_SendTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).SendTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcounter.CounterService/SendTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).SendTable(ctx, req.(*SendTableReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CounterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tcounter.CounterService",
	HandlerType: (*CounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendTable",
			Handler:    _CounterService_SendTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcounter.proto",
}

func init() { proto.RegisterFile("tcounter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x64, 0x9b, 0x46, 0x9a, 0x57, 0x5b, 0xe4, 0x29, 0x1a, 0x7a, 0x8a, 0x39, 0xe5, 0x62, 0xc0,
	0x78, 0xa8, 0x78, 0x54, 0x8a, 0x08, 0x7a, 0x70, 0x5b, 0xbc, 0xa7, 0xe9, 0x3b, 0x84, 0x36, 0xc9,
	0x9a, 0x6c, 0x0a, 0xf9, 0x15, 0xbf, 0x56, 0x76, 0xb7, 0xe9, 0x2a, 0xf4, 0x36, 0x3b, 0xcc, 0xcc,
	0x9b, 0x61, 0x61, 0x2a, 0xb3, 0xaa, 0x2d, 0x25, 0xd5, 0xb1, 0xa8, 0x2b, 0x59, 0xe1, 0xa8, 0x7f,
	0x87, 0xaf, 0xe0, 0x7d, 0xa5, 0xbb, 0x96, 0x56, 0x79, 0xb6, 0x45, 0x84, 0xa1, 0xcc, 0x0b, 0xf2,
	0x59, 0xc0, 0x22, 0x87, 0x6b, 0x8c, 0x17, 0xe0, 0x34, 0x6d, 0xe1, 0x0f, 0x34, 0xa5, 0x20, 0x5e,
	0x81, 0xab, 0xdd, 0xbe, 0x13, 0xb0, 0x68, 0xc8, 0xcd, 0x23, 0x7c, 0x86, 0xc9, 0x8b, 0xc9, 0xfc,
	0x48, 0x85, 0xa0, 0x0d, 0xde, 0x83, 0xb7, 0x57, 0xc9, 0xef, 0x79, 0x23, 0x7d, 0x16, 0x38, 0xd1,
	0x38, 0xb9, 0x8c, 0x8f, 0x3d, 0x8e, 0x47, 0xb9, 0x55, 0x85, 0x3f, 0x0c, 0xce, 0x97, 0x54, 0x6e,
	0x56, 0xe9, 0x7a, 0x47, 0x9c, 0xbe, 0x71, 0x0e, 0xae, 0x54, 0xf8, 0xe0, 0xbf, 0xb5, 0xfe, 0xbf,
	0xb2, 0x58, 0x83, 0x45, 0x29, 0xeb, 0x8e, 0x1b, 0xfd, 0xec, 0x13, 0xc0, 0x92, 0x6a, 0xc3, 0x96,
	0x3a, 0x3d, 0x6b, 0xc2, 0x15, 0xc4, 0x3b, 0x70, 0xf5, 0x59, 0xbd, 0x6b, 0x9c, 0xdc, 0xd8, 0xe0,
	0x7f, 0x23, 0xb8, 0x51, 0x3d, 0x0d, 0x1e, 0x59, 0x08, 0x30, 0x5a, 0x14, 0x42, 0x76, 0xbc, 0x11,
	0xc9, 0x1b, 0x4c, 0x0f, 0xba, 0x25, 0xd5, 0xfb, 0x3c, 0x23, 0x9c, 0x83, 0xd7, 0xf4, 0x95, 0xf0,
	0xfa, 0x74, 0xcf, 0x19, 0x5a, 0xbe, 0x8f, 0x5a, 0x9f, 0xe9, 0x1f, 0x79, 0xf8, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x76, 0x38, 0x66, 0x72, 0xa3, 0x01, 0x00, 0x00,
}
